[package]
name = "laporin-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7", features = ["macros", "multipart"] }
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["cors", "trace", "set-header", "timeout", "fs"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "tls-rustls", "uuid", "chrono", "bigdecimal"] }
tokio = { version = "1.37", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
argon2 = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.10", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = "0.15"
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
base64 = "0.22"
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "rustls-tls", "multipart"] }
url = "2.5"
urlencoding = "2.1"
time = "0.3"
thiserror = "1.0"
axum-extra = { version = "0.9", features = ["cookie"] }
zip = { version = "2.2", default-features = false, features = ["deflate"] }
quick-xml = "0.36"
regex = "1.10"
ipnet = "2.9"
sysinfo = "0.31"
async-trait = "0.1"



[dev-dependencies]
axum-test = "16.4"
tokio-test = "0.4"
tempfile = "3.10"